Repository northpolesec/santa, pull requests merged in 2024-12, with the labels that each got.

#154 Fix: Database Rule Table Version number
  Source/common/BUILD
  Source/santad/DataLayer/SNTDatabaseTable.h
  Source/santad/DataLayer/SNTDatabaseTable.m
  Source/santad/DataLayer/SNTRuleTable.m
  Source/santad/DataLayer/SNTRuleTableTest.m
  Source/santad/Logs/EndpointSecurity/Writers/FSSpool/BUILD
  Source/santad/ProcessTree/BUILD
Labels: bug, daemon, rules

#86 Standalone Mode (Beta) (1/3)
  Source/common/BUILD
  Source/common/SNTCommonEnums.h
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/common/SNTRule.m
  Source/common/SNTSyncConstants.h
  Source/common/SNTSyncConstants.m
  Source/common/SNTXPCNotifierInterface.h
  Source/common/santa.proto
  Source/gui/BUILD
  Source/gui/Resources/de.lproj/Localizable.strings
  Source/gui/Resources/en.lproj/Localizable.strings
  Source/gui/Resources/ru.lproj/Localizable.strings
  Source/gui/Resources/uk.lproj/Localizable.strings
  Source/gui/SNTBinaryMessageWindowController.h
  Source/gui/SNTBinaryMessageWindowController.m
  Source/gui/SNTBinaryMessageWindowView.swift
  Source/gui/SNTFileAccessMessageWindowView.swift
  Source/gui/SNTMessageView.swift
  Source/gui/SNTNotificationManager.m
  Source/gui/SNTNotificationManagerTest.m
  Source/santactl/Commands/SNTCommandFileInfo.m
  Source/santactl/Commands/SNTCommandStatus.m
  Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
  Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
  Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
  Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
  Source/santad/SNTApplicationCoreMetrics.mm
  Source/santad/SNTExecutionController.h
  Source/santad/SNTExecutionController.mm
  Source/santad/SNTNotificationQueue.h
  Source/santad/SNTNotificationQueue.m
  Source/santad/SNTPolicyProcessor.mm
  Source/santad/Santad.mm
  Source/santad/SantadTest.mm
  Source/santasyncservice/SNTSyncEventUpload.mm
  Source/santasyncservice/SNTSyncPreflight.mm
  Source/santasyncservice/SNTSyncTest.mm
  Source/santasyncservice/testdata/sync_preflight_standalone.json
  docs/concepts/mode.md
  docs/deployment/configuration.md
Labels: daemon, 🎅🏻 gui

#159 standalone: Allow password fallback
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/gui/SNTBinaryMessageWindowView.swift
  Source/gui/SNTMessageView.swift
  docs/concepts/mode.md
  docs/deployment/configuration.md
Labels: enhancement

#164 Fix: Add signing ID checks for critical binaries
  Source/santad/DataLayer/SNTRuleTable.m
  Source/santad/DataLayer/SNTRuleTableTest.m
  Source/santad/SNTExecutionControllerTest.mm
  Source/santad/SNTPolicyProcessor.mm
Labels: bug, daemon, rules

#165 Enforce rule add checks on daemon
  Source/common/SNTXPCControlInterface.h
  Source/common/SNTXPCControlInterface.m
  Source/santactl/Commands/SNTCommandRule.m
  Source/santad/SNTDaemonControlController.mm
  Source/santasyncservice/SNTSyncRuleDownload.mm
  Source/santasyncservice/SNTSyncTest.mm
Labels: enhancement, daemon, santactl

#166 Lockdown upgrade fix
  Conf/Package/postinstall
  Conf/install.sh
Labels: bug

#167 Fix upgrade rules teamid
  Conf/Package/postinstall
  Conf/install.sh
Labels: bug

#168 Rename migration plist due to tamper protection rules
  Conf/Package/package.sh
  Conf/Package/postinstall
  Conf/install_services.sh
Labels: bug

#169 One more rename of the migration plist
  Conf/Package/migration.sh
Labels: bug

#173 gui: Update keyboard shortcut for copy details button
  Source/gui/SNTBinaryMessageWindowView.swift
Labels: size/xs, gui

#178 TestGUI: Fix missing replyCallback, make labels in UI verbatim.
  Source/gui/SNTTestGUI.swift
Labels: size/s, gui

#161 Restructure Watch Items objects to prepare for Proc FAA
  Source/santad/BUILD
  Source/santad/DataLayer/WatchItemPolicy.h
  Source/santad/DataLayer/WatchItems.h
  Source/santad/DataLayer/WatchItems.mm
  Source/santad/DataLayer/WatchItemsTest.mm
  Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
  Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Labels: file access authorization

#177 initial Japanese localization
  Source/gui/Resources/ja.lproj/Localizable.strings
Labels: size/s, gui

#180 gui: Use interpolation where needed in strings
  Source/common/BUILD
  Source/gui/Resources/de.lproj/Localizable.strings
  Source/gui/Resources/en.lproj/Localizable.strings
  Source/gui/Resources/ja.lproj/Localizable.strings
  Source/gui/Resources/ru.lproj/Localizable.strings
  Source/gui/Resources/uk.lproj/Localizable.strings
  Source/gui/SNTBinaryMessageWindowView.swift
  Source/gui/SNTMessageView.swift
  Source/gui/SNTTestGUI.swift
  Source/santad/BUILD
Labels: daemon, size/m, gui

#181 Add ring buffer implementation
  Source/common/BUILD
  Source/common/RingBuffer.h
  Source/common/RingBufferTest.mm
Labels: size/m

#174 Standalone: Switch to a hold-and-ask model (part 1)
  Source/common/BUILD
  Source/common/SantaCache.h
  Source/common/SantaCacheTest.mm
  Source/common/SantaVnode.h
  Source/common/SantaVnodeHash.h
  Source/common/SantaVnodeHash.mm
  Source/santad/BUILD
  Source/santad/EventProviders/AuthResultCache.mm
  Source/santad/EventProviders/SNTEndpointSecurityAuthorizer.mm
  Source/santad/EventProviders/SNTEndpointSecurityAuthorizerTest.mm
  Source/santad/EventProviders/SNTEndpointSecurityClient.mm
  Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
  Source/santad/Logs/EndpointSecurity/Serializers/Utilities.mm
  Source/santad/Metrics.mm
  Source/santad/MetricsTest.mm
  Source/santad/SNTDecisionCache.mm
  Source/santad/SNTExecutionController.h
  Source/santad/SNTExecutionController.mm
  Source/santad/SNTNotificationQueue.m
  Source/santad/SantadTest.mm
  Source/santasyncservice/SNTSyncTest.mm
Labels: daemon, size/m, gui

#183 gui: Fix the 'prevent future notifications' label in English
  Source/gui/Resources/de.lproj/Localizable.strings
  Source/gui/Resources/en.lproj/Localizable.strings
  Source/gui/Resources/ru.lproj/Localizable.strings
  Source/gui/Resources/uk.lproj/Localizable.strings
  Testing/localization.py
Labels: size/s, gui

#179 Make SNTRule initWithDictionary case insensitive
  Source/common/SNTConfigurator.m
  Source/common/SNTRule.h
  Source/common/SNTRule.m
  Source/common/SNTRuleTest.m
  Source/santactl/Commands/SNTCommandRule.m
  Source/santad/SNTPolicyProcessorTest.mm
Labels: configurator, daemon, santactl, size/m

#185 Project: Stop pointing at my fork of MOLXPCConnection
  MODULE.bazel
Labels: size/xs

#184 Rework how valid rule IDs are tracked
  Source/common/CertificateHelpers.h
  Source/common/CertificateHelpers.m
  Source/common/SNTCachedDecision.h
  Source/common/SNTCommonEnums.h
  Source/common/SNTStoredEvent.h
  Source/common/SNTStoredEvent.m
  Source/santad/BUILD
  Source/santad/DataLayer/SNTRuleTable.m
  Source/santad/SNTExecutionController.mm
  Source/santad/SNTPolicyProcessor.mm
  Source/santad/SNTPolicyProcessorTest.mm
Labels: daemon, size/m

#186 Add signing status and cs flags to sync proto
  MODULE.bazel
  Source/santasyncservice/SNTSyncEventUpload.mm
Labels: sync protocol, size/s

#187 Track ask and hold mode atomically while processing an event
  Source/santad/SNTExecutionController.mm
Labels: daemon, size/s

#189 Add support for clone and copyfile telemetry events
  Source/common/TelemetryEventMap.h
  Source/common/TelemetryEventMap.mm
  Source/common/TelemetryEventMapTest.mm
  Source/common/santa.proto
  Source/santad/EventProviders/EndpointSecurity/EnrichedTypes.h
  Source/santad/EventProviders/EndpointSecurity/Enricher.mm
  Source/santad/EventProviders/SNTEndpointSecurityRecorder.mm
  Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm
  Source/santad/Logs/EndpointSecurity/Serializers/BasicString.h
  Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
  Source/santad/Logs/EndpointSecurity/Serializers/Empty.h
  Source/santad/Logs/EndpointSecurity/Serializers/Empty.mm
  Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h
  Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
  Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h
  Source/santad/Metrics.mm
  Source/santad/MetricsTest.mm
Labels: daemon, recorder, telemetry, 🪵 logging, size/m

#192 Add serializations for clone and copyfile
  Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
  Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
  Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
  Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
  Source/santad/testdata/protobuf/v1/clone.json
  Source/santad/testdata/protobuf/v2/clone.json
  Source/santad/testdata/protobuf/v4/clone.json
  Source/santad/testdata/protobuf/v4/copyfile.json
  Source/santad/testdata/protobuf/v5/clone.json
  Source/santad/testdata/protobuf/v5/copyfile.json
  Source/santad/testdata/protobuf/v6/clone.json
  Source/santad/testdata/protobuf/v6/copyfile.json
  Source/santad/testdata/protobuf/v7/clone.json
  Source/santad/testdata/protobuf/v7/copyfile.json
  Source/santad/testdata/protobuf/v8/clone.json
  Source/santad/testdata/protobuf/v8/copyfile.json
Labels: daemon, telemetry, size/l

#193 Enforce max size to write for non-null-terminated buffer
  Source/santad/Logs/EndpointSecurity/Writers/Syslog.mm
Labels: daemon, size/xs
